### ISSUE TITLE
Improvements on selected curves

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/mecu#10]
- [x] Remove curve from the bottom has an effect on the graphs
- [x] make the graphs full screen
- [x] finish implementing some of the disi measures https://github.com/sacdallago/disi
- [x] Calculate cohesion index based on known complexes and compare to on-the-fly cohesion index for selected curves (and maybe find outliers, etc. might require a bit more thought than simple implementation and some ML)

**Comment by KlausNie** [comment]
In mecu-graph.js:
```javascript
function findXNeighbours(v, scanline) {
    var f = function (forward, reverse) {
        var it = scanline.findIter(v);
        var u;
        while ((u = it[forward]()) !== null) {
            var uovervX = u.r.overlapX(v.r);
            if (uovervX <= 0 || uovervX <= u.r.overlapY(v.r)) {
                v[forward].insert(u);
                u[reverse].insert(v);
            }
            if (uovervX <= 0) {
                break;
            }
        }
    };
    f("next", "prev");
    f("prev", "next");
}
```

```code
Uncaught TypeError: Cannot read property 'next' of null
    at f (mecu-graph.js:4059)
    at Object.findXNeighbours [as findNeighbours] (mecu-graph.js:4070)
```

seems to be happening when there are multiple proteins with the same name. The points are then drawn all on the same position.

**Comment by sacdallago** [comment]
Done.
