### ISSUE TITLE
Bulk search doesn't render table correctly

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/mecu#11]
When adding proteins to to the search (after an initial rendering) the table doesn't seem to render all headers correctly:

![screen shot 2018-06-19 at 8 05 18 am](https://user-images.githubusercontent.com/6240943/41596258-b8fd2070-7397-11e8-8ac9-4d009e251d30.png)

Might be ahead of time (e.g. the feature is not finished), but reporting just in case.

UPDATE: I seem to understand why you did this (no experiments = no need for header). But then I'd rather have a separate UI element that collects all proteins with no hits.

**Comment by sacdallago** [comment]
@KlausNie with the new table, there still is a visualization issue (e.g. visualizing one protein across multiple experiments:).

![screen shot 2018-08-14 at 2 49 30 pm](https://user-images.githubusercontent.com/6240943/44111913-b2e70a00-9fd1-11e8-8af9-7cfdfb855626.png)

**Comment by KlausNie** [comment]
fix testable in branch unstable.

also reworked the coloring, which should now always match (if a cell is not contained/contained/selected)
