### ISSUE TITLE
No experiment on protein page should select first experiment

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/mecu#61]
If I navigate to https://protein.melting.degree/complex?id=1 I automatically get selected the first experiment (although it's not encoded in the URL). Thus:

```
https://protein.melting.degree/complex?id=1 == https://protein.melting.degree/complex?id=1&experiment=1
```

This behaviour does not happen with protein pages:

```
https://protein.melting.degree/protein?protein=P12004 != https://protein.melting.degree/protein?protein=P12004&experiment=1
```

But it should.

**Comment by KlausNie** [comment]
Resolved by: https://github.com/sacdallago/mecu/pull/62
